# Specify how long a player has to be offline in order to remove them.
# d - Days
# w - weeks
# Example: 2w, 15d
inactive-period: "30d"

# Do you want to check inactive players when the server starts up?
# This will auto remove them.
autoremove-on-start: true

# Should we save who we removed just in case?
# This will create removals.json
save-whitelist-removals: true

config-version: 1