# List any players that will bypass the checks.
# This list has to be UUIDs!
ignored-players:
  - "311be5cd-d17c-49b3-bf47-f781fdbcc929"

# Specify how long a player has to be offline in order to remove them.
# d - Days
# w - weeks
# m - months
# Example: 2w, 15d, 1m
inactive-period: "30d"

# When a player is removed from being inactive, run these commands as well.
# %player% - player's name, might be wrong if they changed it!
# %uuid% - player's UUID.
extra-commands:
#- ban %player%
#- ban %uuid%

# Do you want to check inactive players when the server starts up?
# This will auto remove them.
autoremove-on-start: true

# Should we save whom we removed just in case?
# This will create removals.json
save-whitelist-removals: true

config-version: 3