name: AutoWhitelistRemove
version: ${project.version}
main: lol.hyper.autowhitelistremove.AutoWhitelistRemove
api-version: 1.21
author: hyperdefined
website: https://github.com/hyperdefined/AutoWhitelistRemove/
description: Automatically remove inactive players from your whitelist!
permissions:
  autowhitelistremove.ignore:
    default: op
    description: Allows the usage of /awr ignore.
  autowhitelistremove.check:
    default: op
    description: Allows the usage of /awr check.
  autowhitelistremove.check.confirm:
    default: op
    description: Allows the usage of /awr check confirm.
  autowhitelistremove.reload:
    default: op
    description: Allows the usage of /awr reload.
  autowhitelist.command:
    default: op
    description: Allows the usage of /awr.
commands:
  awr:
    usage: /awr
    permission: autowhitelist.command